/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ClienteDAO;
import controlador.TrabajadorDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Trabajador;

/**
 *
 * @author GrizzALone
 */
public class VentanaMostrar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMostrar
     */
    public VentanaMostrar() {
        initComponents();
        limpiarTablaCli();
        limpiarTablaTra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVerCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRutCli = new javax.swing.JTextField();
        btnBuscarCli = new javax.swing.JButton();
        btnVolverCli = new javax.swing.JButton();
        btnEliminarCli = new javax.swing.JButton();
        btnModificarCli = new javax.swing.JButton();
        btnMostrarTodoCli = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnModificarTra = new javax.swing.JButton();
        btnMostrarTodoTra = new javax.swing.JButton();
        btnEliminarTra = new javax.swing.JButton();
        btnVolverTra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRutTra = new javax.swing.JTextField();
        btnBuscarTra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtVerTrabajador = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(155, 190, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtVerCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Edad", "Telefono", "Saldo", "N° cuenta"
            }
        ));
        jScrollPane1.setViewportView(jtVerCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese el rut:");

        txtRutCli.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRutCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutCliActionPerformed(evt);
            }
        });

        btnBuscarCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnBuscarCli.setText("Buscar");
        btnBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliActionPerformed(evt);
            }
        });

        btnVolverCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverCli.setText("Volver");
        btnVolverCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCliActionPerformed(evt);
            }
        });

        btnEliminarCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnEliminarCli.setText("Eliminar");
        btnEliminarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCliActionPerformed(evt);
            }
        });

        btnModificarCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnModificarCli.setText("Modificar");
        btnModificarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCliActionPerformed(evt);
            }
        });

        btnMostrarTodoCli.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMostrarTodoCli.setText("Mostrar Todo");
        btnMostrarTodoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodoCli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolverCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txtRutCli, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBuscarCli)
                .addGap(286, 286, 286))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCli)
                    .addComponent(jLabel1)
                    .addComponent(txtRutCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnModificarCli)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTodoCli)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverCli))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel3);

        btnModificarTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnModificarTra.setText("Modificar");
        btnModificarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTraActionPerformed(evt);
            }
        });

        btnMostrarTodoTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMostrarTodoTra.setText("Mostrar Todo");
        btnMostrarTodoTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoTraActionPerformed(evt);
            }
        });

        btnEliminarTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnEliminarTra.setText("Eliminar");
        btnEliminarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTraActionPerformed(evt);
            }
        });

        btnVolverTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverTra.setText("Volver");
        btnVolverTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverTraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Ingrese el rut:");

        txtRutTra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRutTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutTraActionPerformed(evt);
            }
        });

        btnBuscarTra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnBuscarTra.setText("Buscar");
        btnBuscarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTraActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(614, 237));

        jtVerTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Edad", "Telefono", "Sueldo base", "Cargo"
            }
        ));
        jScrollPane3.setViewportView(jtVerTrabajador);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminarTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTodoTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(txtRutTra, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBuscarTra)
                .addGap(286, 286, 286))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarTra)
                    .addComponent(txtRutTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnModificarTra)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTodoTra)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverTra))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Trabajador", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutCliActionPerformed

    private void btnVolverCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCliActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverCliActionPerformed

    private void btnMostrarTodoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoCliActionPerformed
        limpiarTablaCli();
        ClienteDAO cli = new ClienteDAO();
        ArrayList<Cliente> clientes = cli.obtenerClientes();
        if(clientes.size()==0){
            JOptionPane.showMessageDialog(this, "No hay clientes para mostrar");
        }else{
            DefaultTableModel dtm=(DefaultTableModel)jtVerCliente.getModel();
            String [][] datos=new String[clientes.size()][6];
            for (int i = 0; i < clientes.size(); i++) {
                datos[i][0]=clientes.get(i).getRut();
                datos[i][1]=clientes.get(i).getNombre();
                datos[i][2]=String.valueOf(clientes.get(i).getEdad())+" años";
                datos[i][3]=String.valueOf(clientes.get(i).getTelefono());
                datos[i][4]="$ "+String.valueOf(clientes.get(i).getSaldo());
                datos[i][5]=clientes.get(i).getNumCuenta();

                dtm.addRow(datos[i]);
            }
            jtVerCliente.setModel(dtm);
        }
    }//GEN-LAST:event_btnMostrarTodoCliActionPerformed

    private void btnBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliActionPerformed
        limpiarTablaCli();
        ClienteDAO cli = new ClienteDAO();
        Cliente cc = cli.buscarCliente(txtRutCli.getText());
        
        if(cc==null){
            JOptionPane.showMessageDialog(this, "No existe el rut del cliente");
        }else{
            DefaultTableModel dtm=(DefaultTableModel)jtVerCliente.getModel();
            String [] datos=new String[6];
            datos[0]=cc.getRut();
            datos[1]=cc.getNombre();
            datos[2]=String.valueOf(cc.getEdad())+" años";
            datos[3]=String.valueOf(cc.getTelefono());
            datos[4]="$ "+String.valueOf(cc.getSaldo());
            datos[5]=cc.getNumCuenta();
            
            dtm.addRow(datos);
            jtVerCliente.setModel(dtm);
        }
    }//GEN-LAST:event_btnBuscarCliActionPerformed

    private void btnModificarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCliActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jtVerCliente.getModel();
        int fila=jtVerCliente.getSelectedRow();
        if(fila==-1)
        JOptionPane.showMessageDialog(this, "Debe seleccionar el cliente");
        else
        {
            String rut=String.valueOf(jtVerCliente.getValueAt(fila, 0));
            String nombre=String.valueOf(jtVerCliente.getValueAt(fila, 1));
            int edad=Integer.parseInt(String.valueOf(jtVerCliente.getValueAt(fila, 2)).replace(" años", ""));
            int telefono=Integer.parseInt(String.valueOf(jtVerCliente.getValueAt(fila, 3)));
            int saldo=Integer.parseInt(String.valueOf(jtVerCliente.getValueAt(fila, 4)).replace("$ ", ""));
            String numCuenta=String.valueOf(jtVerCliente.getValueAt(fila, 5));
            
            Cliente cc=new Cliente(rut, nombre, edad, telefono, saldo, numCuenta);
            ClienteDAO cliDAO=new ClienteDAO();
            cliDAO.modificarCliente(cc);
            JOptionPane.showMessageDialog(this, "Cliente modificado");
        }
    }//GEN-LAST:event_btnModificarCliActionPerformed

    private void btnEliminarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCliActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jtVerCliente.getModel();
        int fila=jtVerCliente.getSelectedRow();
        if(fila==-1)
        JOptionPane.showMessageDialog(this, "Debe seleccionar el cliente");
        else
        {
            String rut=String.valueOf(jtVerCliente.getValueAt(fila, 0));
            ClienteDAO cliDAO=new ClienteDAO();
            cliDAO.eliminarCliente(rut);
            JOptionPane.showMessageDialog(this,"Cliente Eliminado");
            dtm.removeRow(fila);
        }
    }//GEN-LAST:event_btnEliminarCliActionPerformed

    private void btnModificarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTraActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jtVerTrabajador.getModel();
        int fila=jtVerTrabajador.getSelectedRow();
        if(fila==-1)
        JOptionPane.showMessageDialog(this, "Debe seleccionar el trabajador");
        else
        {
            String rut=String.valueOf(jtVerTrabajador.getValueAt(fila, 0));
            String nombre=String.valueOf(jtVerTrabajador.getValueAt(fila, 1));
            int edad=Integer.parseInt(String.valueOf(jtVerTrabajador.getValueAt(fila, 2)).replace(" años", ""));
            int telefono=Integer.parseInt(String.valueOf(jtVerTrabajador.getValueAt(fila, 3)));
            int sueldoBase=Integer.parseInt(String.valueOf(jtVerTrabajador.getValueAt(fila, 4)).replace("$ ", ""));
            String cargo=String.valueOf(jtVerTrabajador.getValueAt(fila, 5));
            
            Trabajador tt=new Trabajador(rut, nombre, edad, telefono, sueldoBase, cargo);
            TrabajadorDAO traDAO=new TrabajadorDAO();
            traDAO.modificarTrabajador(tt);
            JOptionPane.showMessageDialog(this, "Trabajador modificado");
        }
    }//GEN-LAST:event_btnModificarTraActionPerformed

    private void btnEliminarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTraActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jtVerTrabajador.getModel();
        int fila=jtVerTrabajador.getSelectedRow();
        if(fila==-1)
        JOptionPane.showMessageDialog(this, "Debe seleccionar el trabajador");
        else
        {
            String rut=String.valueOf(jtVerTrabajador.getValueAt(fila, 0));
            TrabajadorDAO traDAO=new TrabajadorDAO();
            traDAO.eliminarTrabajador(rut);
            JOptionPane.showMessageDialog(this,"Trabajador Eliminado");
            dtm.removeRow(fila);
        }
    }//GEN-LAST:event_btnEliminarTraActionPerformed

    private void btnVolverTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverTraActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverTraActionPerformed

    private void txtRutTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutTraActionPerformed

    private void btnBuscarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTraActionPerformed
        limpiarTablaTra();
        TrabajadorDAO tra=new TrabajadorDAO();
        Trabajador tt = tra.buscarTrabajador(txtRutTra.getText());
        
        if(tt==null){
            JOptionPane.showMessageDialog(this, "No existe el rut del Trabajador");
        }else{
            DefaultTableModel dtm=(DefaultTableModel)jtVerTrabajador.getModel();
            String [] datos=new String[6];
            datos[0]=tt.getRut();
            datos[1]=tt.getNombre();
            datos[2]=String.valueOf(tt.getEdad())+" años";
            datos[3]=String.valueOf(tt.getTelefono());
            datos[4]="$ "+String.valueOf(tt.getSueldoBase());
            datos[5]=tt.getCargo();
            
            dtm.addRow(datos);
            jtVerTrabajador.setModel(dtm);
        }
    }//GEN-LAST:event_btnBuscarTraActionPerformed

    private void btnMostrarTodoTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoTraActionPerformed
        limpiarTablaTra();
        TrabajadorDAO tra = new TrabajadorDAO();
        ArrayList<Trabajador> trabajadores = tra.obtenerTrabajadores();
        if(trabajadores.size()==0){
            JOptionPane.showMessageDialog(this, "No hay trabajadores para mostrar");
        }else{
            DefaultTableModel dtm=(DefaultTableModel)jtVerTrabajador.getModel();
            String [][] datos=new String[trabajadores.size()][6];
            for (int i = 0; i < trabajadores.size(); i++) {
                datos[i][0]=trabajadores.get(i).getRut();
                datos[i][1]=trabajadores.get(i).getNombre();
                datos[i][2]=String.valueOf(trabajadores.get(i).getEdad())+" años";
                datos[i][3]=String.valueOf(trabajadores.get(i).getTelefono());
                datos[i][4]="$ "+String.valueOf(trabajadores.get(i).getSueldoBase());
                datos[i][5]=trabajadores.get(i).getCargo();

                dtm.addRow(datos[i]);
            }
            jtVerTrabajador.setModel(dtm);
        }
    }//GEN-LAST:event_btnMostrarTodoTraActionPerformed

    public void limpiarTablaCli(){
       DefaultTableModel dtm=(DefaultTableModel)jtVerCliente.getModel();
       int n=jtVerCliente.getRowCount()-1;
       for (int i = 0; i <=n; i++) {
           dtm.removeRow(dtm.getRowCount()-1);
       }
   }
    
    public void limpiarTablaTra(){
       DefaultTableModel dtm=(DefaultTableModel)jtVerTrabajador.getModel();
       int n=jtVerTrabajador.getRowCount()-1;
       for (int i = 0; i <=n; i++) {
           dtm.removeRow(dtm.getRowCount()-1);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarTra;
    private javax.swing.JButton btnEliminarCli;
    private javax.swing.JButton btnEliminarTra;
    private javax.swing.JButton btnModificarCli;
    private javax.swing.JButton btnModificarTra;
    private javax.swing.JButton btnMostrarTodoCli;
    private javax.swing.JButton btnMostrarTodoTra;
    private javax.swing.JButton btnVolverCli;
    private javax.swing.JButton btnVolverTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtVerCliente;
    private javax.swing.JTable jtVerTrabajador;
    private javax.swing.JTextField txtRutCli;
    private javax.swing.JTextField txtRutTra;
    // End of variables declaration//GEN-END:variables
}
