/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author GrizzALone
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_ingresar = new javax.swing.JMenuItem();
        menuMostrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menu_ingresar.setText("Ingresar");
        menu_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ingresarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_ingresar);

        menuMostrar.setText("Mostrar");
        menuMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(menuMostrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        dispose();
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ingresarActionPerformed
        VentanaIngreso ven=new VentanaIngreso();
        ven.setTitle("Formulario de Ingreso");
        ven.setResizable(false);
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
    }//GEN-LAST:event_menu_ingresarActionPerformed

    private void menuMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMostrarActionPerformed
        VentanaMostrar ven=new VentanaMostrar();
        ven.setTitle("Mostrando datos");
        ven.setResizable(false);
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuMostrar;
    private javax.swing.JMenuItem menu_ingresar;
    private javax.swing.JMenuItem menu_salir;
    // End of variables declaration//GEN-END:variables
}
